name: latest
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'recursive'
      - name: Publish site
        run: |
          hugo -t cactus
          rsync -a -v --delete-after ./public/ /data/blog 
